// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTzJFdzHAkwOZiQ1t6xxgNICaTZKeEgP4',
    appId: '1:988154685868:web:b1fba88cc1475071d43209',
    messagingSenderId: '988154685868',
    projectId: 'health-room-2ff2e',
    authDomain: 'health-room-2ff2e.firebaseapp.com',
    storageBucket: 'health-room-2ff2e.appspot.com',
    measurementId: 'G-D7J1BHTTD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE2h1L6jFAEC3RQ4M3KfMd11Lvs0IlXp4',
    appId: '1:988154685868:android:bbac70bfe8441c00d43209',
    messagingSenderId: '988154685868',
    projectId: 'health-room-2ff2e',
    storageBucket: 'health-room-2ff2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcuBCo_W0XSowthlVqL0vTKkpgvWSrl9w',
    appId: '1:988154685868:ios:e33ff73abc0792e3d43209',
    messagingSenderId: '988154685868',
    projectId: 'health-room-2ff2e',
    storageBucket: 'health-room-2ff2e.appspot.com',
    iosClientId: '988154685868-lamgmh8vikqtm2bkj21qaktso4q90s74.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthroomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcuBCo_W0XSowthlVqL0vTKkpgvWSrl9w',
    appId: '1:988154685868:ios:e33ff73abc0792e3d43209',
    messagingSenderId: '988154685868',
    projectId: 'health-room-2ff2e',
    storageBucket: 'health-room-2ff2e.appspot.com',
    iosClientId: '988154685868-lamgmh8vikqtm2bkj21qaktso4q90s74.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthroomApp',
  );
}
